version: '2'
services:
    bookstore-postgresql:
        image: postgres:10.4
        # volumes:
        #     - ~/volumes/jhipster/bookstore/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=bookstore
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
