---
path: .
instances: 1
buildpack: https://github.com/cloudfoundry/java-buildpack
services:
- mycoolbookstore
applications:
- name: mycoolbookstore
  env:
    SPRING_PROFILES_ACTIVE: prod, cloudfoundry
